# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: richarmamadi03
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: crud-cloud
# "service" is the name of this project. This will also be added to your AWS resource names.
service: cloud-computing-lab3

provider: 
  name: aws 
  runtime: nodejs24.x 
  architecture: arm64 
  region: us-east-1 
  environment: 
    CITAS_TABLE: ${self:service}-citas-${sls:stage} 
  iam: 
    role: 
      statements: 
        - Effect: Allow 
          Action: 
            - dynamodb:PutItem 
            - dynamodb:GetItem 
            - dynamodb:Scan 
            - dynamodb:UpdateItem 
            - dynamodb:DeleteItem 
          Resource: 
            - Fn::GetAtt: [CitasTable, Arn]
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions: 
  crear: 
    handler: handler.crear 
    events: 
      - httpApi: 
          path: /citas 
          method: post 
  listar: 
    handler: handler.listar 
    events: 
      - httpApi: 
          path: /citas 
          method: get 
  obtener: 
    handler: handler.obtener 
    events: 
      - httpApi: 
          path: /citas/{id} 
          method: get 
  actualizar: 
    handler: handler.actualizar 
    events: 
      - httpApi: 
          path: /citas/{id} 
          method: put 
  eliminar: 
    handler: handler.eliminar 
    events: 
      - httpApi: 
          path: /citas/{id} 
          method: delete

resources: 
  Resources: 
    CitasTable: 
      Type: AWS::DynamoDB::Table 
      Properties: 
        TableName: ${self:provider.environment.CITAS_TABLE} 
        BillingMode: PAY_PER_REQUEST 
        AttributeDefinitions: 
          - AttributeName: id 
            AttributeType: S 
        KeySchema: 
          - AttributeName: id 
            KeyType: HASH 

plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  serverless-dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      docker: true
      # En lugar de utilizar docker usar podman
      dockerPath: "podman"
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true
